version: 2
jobs:
  asan:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/install_dependencies.sh
      - run: ./ci/do_ci.sh cmake.asan
      - store_artifacts:
          path: /build/Testing/Temporary/LastTest.log
          destination: Test.log
  tsan:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: mkdir -p /build
      - run: ./ci/install_dependencies.sh
      - run: BUILD_DIR=/build ./ci/do_ci.sh cmake.tsan
      - store_artifacts:
          path: /build/Testing/Temporary/LastTest.log
          destination: Test.log
  bazel:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/install_dependencies.sh
      - run: ./ci/install_bazel.sh
      - run: ./ci/do_ci.sh bazel.build
  plugin:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/do_ci.sh cmake.plugin
      - store_artifacts:
          path: /libzipkin_opentracing_plugin.so
          destination: libzipkin_opentracing_plugin.so
  release:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get -qq update; apt-get -y install git ssh
      - checkout
      - run: ./ci/do_ci.sh release

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - asan
      - tsan
      - bazel
      - plugin
