workspace(name = "com_github_rnburn_zipkin_opentracing")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "io_opentracing_cpp",
    remote = "https://github.com/opentracing/opentracing-cpp",
    commit = "ac50154a7713877f877981c33c3375003b6ebfe1",
)

new_local_repository(
    name = "se_haxx_curl_libcurl",
    path = "/usr",
    build_file = "BUILD.curl"
)
