workspace(name = "com_github_rnburn_zipkin_opentracing")

git_repository(
    name = "io_opentracing_cpp",
    remote = "https://github.com/opentracing/opentracing-cpp",
    commit = "44e74489586550c388cca92f3ece187b3f1bf5d5",
)

new_local_repository(
    name = "se_haxx_curl_libcurl",
    path = "/usr",
    build_file = "BUILD.curl"
)
